# This service get all the frames from the teaching pandanat
# the frames based on the "base" frame should follow the name convention: P[non negative number less than 100], e.g., P0 P1 P32 ... P99


---
bool success
string error

int32 frame_size

string[] frame_name
string[] parent_name

# frame data 
int32[] status
JointQuantity[] joint_position
geometry_msgs/Pose[] cart_world_position
