# This service allows to set a control mode at runtime.
# The user can select control modes defined in iiwa_msgs/ControlMode and set the respective parameters accordingly to the selected mode.



---
bool success
string error

int32 frame_size

string[] frame_name
string[] parent_name

JointQuantity[] joint_position
geometry_msgs/Pose[] cart_world_position
